options:
  metrics-port:
    type: int
    default: 8681
    description: Port to expose the liveness metrics
  csi-config:
    type: string
    default: "[]"
    description: JSON string of CSI configuration
