options:
  metrics-port:
    type: int
    default: 8681
    description: Port to expose the liveness metrics
  cluster-id:
    type: string
    default: ""
    description: Ceph cluster ID
  fs-name:
    type: string
    default: "kubernetes"
    description: "Ceph fs name"
  pool-name:
    type: string
    default: "kubernetes"
    description: "Ceph pool name"
  fs-type:
    type: string
    default: "ext4"
    description: "Ceph filesystem type"
  reclaim-policy:
    type: string
    default: "Delete"
    description: "StorageClass reclaim policy"
  allow-volume-expansion:
    type: boolean
    default: true
    description: "StorageClass allow expansion"
  mount-options:
    type: string
    default: "discard"
    description: "Comma separated StorageClass mount options"
